[package]
name = "nofrills-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
base64 = "0.22.1"
crab_nbt = "0.2.9"
dotenvy = "0.15.7"
flate2 = "1.1.5"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
ureq = "3.0.11"
